name: Generate Profile Image

on:
  push:
    branches: [main]
    paths:
      - 'profile.py'
      - 'Makefile'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install freeze via .deb package
        run: |
          curl -LO https://github.com/charmbracelet/freeze/releases/download/v0.2.2/freeze_0.2.2_amd64.deb
          sudo dpkg -i freeze_0.2.2_amd64.deb

      - name: Generate Profile Image
        run: |
          make

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          if [[ -n "$(git status --porcelain assets/profile.png)" ]]; then
            git add assets/profile.png
            git commit -m "ci: update profile image"
            git push
          else
            echo "No changes to commit"
          fi
