name: Generate Profile Image

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure profile.py exists and is not empty
        run: |
          if [ ! -s ./profile.py ]; then
            echo "profile.py is missing or empty"
            exit 1
          fi

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install Freeze
        run: go install github.com/charmbracelet/freeze@latest

      - name: Generate Profile Image
        run: make image

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          if [[ -n "$(git status --porcelain assets/profile.png)" ]]; then
            git add assets/profile.png
            git commit -m "ci: update profile image"
            git push || {
              echo "Failed to push changes"
              exit 1
            }
          else
            echo "No changes to commit"
          fi
